title: Domspatzen Kurs Algorithmik
description: >
  Website zur Verteilung der Kursmaterialien
permalink: ':title/'
baseurl: "/"
url: "https://algorithmik-kurs.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Rene Gr√ºnbauer

# Disqus
#discus-identifier: # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
