title: Domspatzen Kurs Algorithmik
description: >
  Website zur Verteilung der Kursmaterialien
permalink: ':title/'
baseurl: ""
url: "https://algorithmik-kurs.github.io/"

author: Jonathan Treffler

# Tracker
#analytics: # Google Analytics

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed
paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
